# Generated by Django 5.0.1 on 2024-01-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=30, verbose_name='Тема')),
                ('date', models.DateField(verbose_name='Дата и время')),
                ('is_shkn', models.BooleanField(verbose_name='Шкн в названии')),
                ('is_link', models.BooleanField(verbose_name='Есть ссылка')),
                ('appointment', models.CharField(max_length=50, verbose_name='Назначение')),
            ],
        ),
    ]
